---
- name: Install wget, tmux and unzip
  ansible.builtin.apt:
    pkg:
    - wget
    - tmux
    - unzip
    state: present
    update_cache: true

- name: Unzip server file
  become: true
  ansible.builtin.unarchive:
    src: "{{ server_url }}"
    dest: /srv/terraria/"{{ server_file }}"
    remote_src: yes

- name: Change file permissions
  become: true
  ansible.builtin.file:
    path: /srv/terraria/"{{ server_file }}"
    owner: terraria
    group: terraria
    mode: '0744'
