---
- name: Put on system the server service
  ansible.builtin.template:
    src: terraria-server.service.j2
    dest: /etc/systemd/system/terraria-server.service
# Notify is used to call declared handlers
  notify:
    - Daemon Reload 
    - Enable server

- name: Add terraria user to sudoers
  community.general.sudoers:
    name: terraria
    state: present
    user: terraria
    commands:
      - /bin/systemctl restart terraria-server.service
      - /bin/systemctl start terraria-server.service
      - /bin/systemctl enable terraria-server.service
      - /bin/systemctl status terraria-server.service
