---
- name: Install wget, tmux and unzip
  ansible.builtin.apt:
    pkg:
    - wget
    - tmux
    - unzip
    state: present
    update_cache: true

- name: Get server zip file
  become: true
  ansible.builtin.get_url:
    url: "{{ server_url }}"
    dest: /srv/terraria
    owner: terraria
    group: terraria

